# Generated by Django 5.2.17 on 2026-10-06 05:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000)])),
                ('merchant_category', models.CharField(choices=[('Retail', 'Retail'), ('Groceries', 'Groceries'), ('Dining', 'Dining'), ('Travel', 'Travel'), ('Electronics', 'Electronics'), ('Entertainment', 'Entertainment'), ('Services', 'Services')], max_length=30)),
                ('transaction_type', models.CharField(choices=[('In-store', 'In-store'), ('Online', 'Online'), ('ATM', 'ATM'), ('Contactless', 'Contactless')], max_length=20)),
                ('card_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Prepaid', 'Prepaid')], max_length=15)),
                ('country', models.CharField(choices=[('US', 'United States'), ('GB', 'United Kingdom'), ('ID', 'Indonesia'), ('DE', 'Germany'), ('SG', 'Singapore'), ('AU', 'Australia'), ('JP', 'Japan')], max_length=2)),
                ('device_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Desktop', 'Desktop'), ('Terminal', 'Terminal')], max_length=15)),
                ('previous_transactions_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('average_transaction_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000)])),
                ('transaction_frequency', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('distance_from_home', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)])),
                ('distance_from_last_transaction', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)])),
                ('ratio_to_median_purchase_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000)])),
                ('used_chip', models.BooleanField(default=True)),
                ('used_pin_number', models.BooleanField(default=True)),
                ('online_order', models.BooleanField(default=False)),
                ('predicted_class', models.BooleanField(default=False, verbose_name='Flagged as potential fraud')),
                ('fraud_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('model_version', models.CharField(default='unknown', max_length=50)),
                ('decision_threshold', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_demo', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_datetime', '-id'],
                'indexes': [models.Index(fields=['transaction_datetime'], name='detection_t_transac_0bf156_idx'), models.Index(fields=['predicted_class', 'risk_level'], name='detection_t_predict_4fcf65_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_positive_amount'), models.CheckConstraint(condition=models.Q(('fraud_probability__gte', 0), ('fraud_probability__lte', 1)), name='probability_between_zero_and_one')],
            },
        ),
    ]
