"""Lazy cached inference from a trusted, project-owned Joblib artifact."""
import logging
import math
from functools import lru_cache
from pathlib import Path
import joblib
from django.conf import settings
from .preprocessing import feature_frame
from .schema import FEATURES, SCHEMA_VERSION

logger = logging.getLogger(__name__)


class ModelUnavailableError(Exception):
    """The local model is missing, incompatible or failed inference."""


@lru_cache(maxsize=2)
def _load(path, modified_ns, size):
    # Joblib uses pickle: only load artifacts generated by this repository.
    try:
        artifact = joblib.load(path)
        if artifact.get("schema_version") != SCHEMA_VERSION or artifact.get("features") != FEATURES:
            raise ValueError("Incompatible model schema.")
        if not 0 < artifact["threshold"] < 1 or not hasattr(artifact["pipeline"], "predict_proba"):
            raise ValueError("Invalid model artifact.")
        return artifact
    except Exception as exc:
        logger.warning("Cannot load model artifact: %s", type(exc).__name__)
        raise ModelUnavailableError("The analysis model is unavailable. Run python manage.py train_model to prepare it.") from exc


def load_model():
    path = Path(settings.MODEL_PATH)
    try:
        stat = path.stat()
    except OSError as exc:
        raise ModelUnavailableError("The analysis model is unavailable. Run python manage.py train_model to prepare it.") from exc
    return _load(str(path.resolve()), stat.st_mtime_ns, stat.st_size)


def classify_risk(probability):
    return "low" if probability < 0.30 else "medium" if probability <= 0.70 else "high"


def predict_transactions(records):
    frame = feature_frame(records)
    artifact = load_model()
    try:
        probabilities = artifact["pipeline"].predict_proba(frame)[:, 1]
        output = []
        for probability in probabilities:
            probability = float(probability)
            if not math.isfinite(probability) or not 0 <= probability <= 1:
                raise ValueError("Invalid probability returned by model.")
            output.append({"predicted_class": probability >= artifact["threshold"], "fraud_probability": probability,
                           "risk_level": classify_risk(probability), "model_version": artifact["model_version"],
                           "decision_threshold": float(artifact["threshold"])})
        return output
    except Exception as exc:
        logger.warning("Model inference failed: %s", type(exc).__name__)
        raise ModelUnavailableError("Analysis is temporarily unavailable. Please retrain the local model and try again.") from exc


def predict_transaction(data):
    return predict_transactions([data])[0]
